[package]
name = "fwatch"
version = "0.2.0"
authors = ["Eugene Marcotte <emarcotte@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
clap = "2.33.0"
futures = "0.1"
ignore = "0.4.7"
inotify = "0.7.0"
os_pipe = "0.8.1"
regex = "1.1.7"
shared_child = "0.3.3"
